name: video_compress
description: A new flutter plugin project.
version: 0.0.1
#author: q1<zonggeu@gmail.com>
homepage: https://github.com/ahyangnb/video_compress

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    androidPackage: com.video.compress.video_compress
    pluginClass: VideoCompressPlugin
